#pragma once
#include "./splitH.h"
#include "./printH.h"
#include "../structs/ListNode.h"
#include "../structs/nextNode.h"
#include "../structs/nNode.h"
#include "../structs/TreeNode.h"
#include <vector>
#include <unordered_map>
#include <algorithm>